### ISSUE TITLE
Drop support for python 2.6 ?

### ISSUE THREAD

**Issue by JocelynDelalande** [slimta/python-slimta#30]
Open question : does supporting python 2.6 worth the effort ?

I just started hacking around with slimta, and already noticed 2 times python2.6 was not blocking me but made the things a bit less elegant:

- the use of unittest2 dependency
- the usage of several context managers in a single call

I know 2.6-> 2.7 is a big usefull version and expect to face other cases. Also, python 2.7 API is quite designed to be easy to build programs running with both python2 and python3 (see #26 ), all major distros have benn on py2.7 for years so, what remains ?

@icgood what do you think ? (open question)

**Comment by icgood** [comment]
That is a good question. Python 2.6 was not supported until version `0.3.21` or so (early last year), when I added it simply because it was easy ([this diff](https://github.com/slimta/python-slimta/compare/df246e9ce122abc0dee677850f22f0cea0e55968...705c786866dc1cf147233e9d77535e17cebbd5e8)).

Python 2.6 is the still the standard version on CentOS and RHEL 6, which makes up a fairly massive population of enterprise servers. However, I don't think enterprise is a target audience for slimta :smiley: and even in those cases there are 2.7 packages available from third-party repos.

There is the [six](https://pypi.python.org/pypi/six) library which covers most of the more difficult compatibility issues, but I think I would rather drop support for 2.6 than pursue the fairly inelegant six integration.

**Comment by JocelynDelalande** [comment]
Cool :) I'm using six anyway, for python3 compat, but we will be able to reduce its use significantly in a second time if we drop 2.6 compat.

**Comment by icgood** [comment]
Python 2.6 support has been dropped in the latest `master` commits, and will be dropped in all versions >= 3.0.0, which should be tagged shortly.
