### ISSUE TITLE
Coverage does not count some files

### ISSUE THREAD

**Issue by JocelynDelalande** [slimta/python-slimta#35]
For ex if you look at https://ci.slimta.org/job/python-slimta-PR/7/PYTHON=CPython-2.7/cobertura/slimta_policy/

You can see that slimta.policy.spamassassin is missing. It seems that the only files taken into account are the ones where the tests goes at least one time.

**Comment by icgood** [comment]
Hmm. That is interesting.

I noticed that behavior a while back when working on another project, I switched from `nosetests` to `py.test` and suddenly my coverage dropped significantly. I may look at the switch for slimta repos as well, since I generally like it better and it seems to be better suited for an eventual switch to Travis CI.

**Comment by icgood** [comment]
`python-slimta` and all extensions are now using `py.test`, whose code coverage plugin (`--cov=slimta`) count all files.
