### ISSUE TITLE
Using environment markers require recent version of setuptools

### ISSUE THREAD

**Issue by JocelynDelalande** [slimta/python-slimta#42]
Good move to introduce env markers in 7f3b733393ec10ee4f90de5571dbc1ea81af01d8 that's the proper way to do. 

Sadly, with setuptools/pip versions from Debian jessie, using env markers fail:

```
$ mkvirtualenv -p /usr/bin/python3 slimta
(slimta) $ pip install -e git+https://github.com/slimta/python-slimta.git#egg=python_slimta
Obtaining python-slimta from git+https://github.com/slimta/python-slimta.git#egg=python_slimta
  Updating /home/jocelyn/.virtualenvs/yom/src/python-slimta clone
  Running setup.py (path:/home/jocelyn/.virtualenvs/yom/src/python-slimta/setup.py) egg_info for package python-slimta
    error in python-slimta setup command: Invalid environment marker: python_version <  "3.0"
    Complete output from command python setup.py egg_info:
    error in python-slimta setup command: Invalid environment marker: python_version <  "3.0"
```
That fixes it :

    pip install -U setuptools 

But, that makes the installation a two stage process, removing the "simple as pip install" thing.

So IMHO, reverting 7f3b733393ec10ee4f90de5571dbc1ea81af01d8 is the way, what do you think ?

The other option is to amend README.md mentioning to `pip install -U pip`

**Comment by icgood** [comment]
Yeah, I noticed the same on my end. I added a note to the README that mentions this.

There are several reasons I prefer suggesting the upgrade, rather than reverting 7f3b733:

* I intend to start uploading wheel distributions to PyPi. These distributions do not execute `setup.py`, so only work if logic is handled by environment markers. This seems to be the direction the Python dist community is settling on.
* The upgrade only needs to be run in the slimta virtualenv, not system-wide. I don't know how people are using slimta in "production" environments, but I still use a virtualenv in `/opt/slimta` on my servers.
* When using an if/else in the `setup.py` script, every time I switched virtualenv's to a different version of Python dependency resolution would fail until I re-ran `python setup.py develop`.
