### ISSUE TITLE
Incompatibility with Django

### ISSUE THREAD

**Issue by JocelynDelalande** [slimta/python-slimta#43]
Working on an application using both Django & slimta (and thus gevent).

There is some errors with Django dev tools (test runner, and devserver) :

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/jocelyn/.virtualenvs/gevent3/lib/python3.4/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/home/jocelyn/.virtualenvs/gevent3/lib/python3.4/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jocelyn/.virtualenvs/gevent3/lib/python3.4/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/jocelyn/.virtualenvs/gevent3/lib/python3.4/site-packages/django/core/management/base.py", line 360, in run_from_argv
    connections.close_all()
  File "/home/jocelyn/.virtualenvs/gevent3/lib/python3.4/site-packages/django/db/utils.py", line 235, in close_all
    connection.close()
  File "/home/jocelyn/.virtualenvs/gevent3/lib/python3.4/site-packages/django/db/backends/base/base.py", line 263, in close
    self.validate_thread_sharing()
  File "/home/jocelyn/.virtualenvs/gevent3/lib/python3.4/site-packages/django/db/backends/base/base.py", line 523, in validate_thread_sharing
    % (self.alias, self._thread_ident, thread.get_ident()))
django.db.utils.DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id 140001273534208 and this is thread id 140001196547568.
```
That's caused by the gevent monkey-*patch_all()* of the threading, one [suggested solution](https://code.djangoproject.com/ticket/17998#comment:6) is not to patch threading :

```
 gevent.monkey.patch_all(socket=True, dns=True, time=True, select=True,thread=False, os=True, ssl=True, httplib=False, aggressive=True)
```
This suggestion seems fine to be but as I'm not expert at all with gevent, I prefer to ask before submiting patch : would this theoretically break slimta ?

**Comment by icgood** [comment]
Interesting that you're seeing that error. I went to great pains to make sure slimta _didn't_ require monkey-patching, but there are some things worth noting:

* The `dnspython` library requires monkey-patching, so it is done inside a context manager that reverts the patching afterwards: [`slimta.util:63`](https://github.com/slimta/python-slimta/blob/master/slimta/util/__init__.py#L63)
* The current example script `slimta-mail.py` calls `monkey.patch_all()`. That is done as a "suggestion" not a requirement, since people will often build on the example script and may not be very familiar with gevent. I will add a note there to clarify.

If you are monkey-patching in your code, look through and see if you directly or indirectly use any blocking Python calls. If those can be converted to equivalent gevent calls, then you don't need to monkey-patch. If they cannot, and you do need to monkey-patch, put the code in a helper module and use [`with slimta.util.monkeypatch_all():`](https://slimta.org/latest/api/slimta.util.html#slimta.util.monkeypatch_all) around the import.

**Comment by JocelynDelalande** [comment]
> Interesting that you're seeing that error. I went to great pains to make sure slimta didn't require monkey-patching, but there are some things worth noting:
> 
>     The dnspython library requires monkey-patching, so it is done inside a context manager that reverts the patching afterwards: slimta.util:63

Yes, that's because of this patching that it fails. If I remove this context-managed `patch_all`, error vanishes (but slimta MX-related stuff is no longer usable...).

>     The current example script slimta-mail.py calls monkey.patch_all(). That is done as a "suggestion" not a requirement, since people will often build on the example script and may not be very familiar with gevent. I will add a note there to clarify.

Yep, but I'm not monkey-patching on my own, that's really the dnspython patching that messes things up.

I'm experimentating removing threading patching, but dnspython [do use threading](https://github.com/rthalley/dnspython/blob/40dcfc8c20c2c732e4384f20b83baa783c6c78b0/dns/entropy.py) for crypto :-/.

**Comment by icgood** [comment]
Ahh well that sucks.

I am very interested in this project: https://bitbucket.org/paulc/dnslib/

It seems like it would make implementing MX lookup fairly easy using "native" gevent.

**Comment by JocelynDelalande** [comment]
> I am very interested in this project: https://bitbucket.org/paulc/dnslib/
> 
> It seems like it would make implementing MX lookup fairly easy using "native" gevent.

Yeah, and if it could suck less than dnspython in terms of py2/py3 packaging, it wouldn't hurt either :)
