### ISSUE TITLE
Any way of closing the socket during a SmtpSession validation?

### ISSUE THREAD

**Issue by thestick613** [slimta/python-slimta#57]
I can easily set reply.code = '5xx' during any part of the SmtpSession validation, but i would sometimes like to close the socket of the client connecting to my SmtpEdge as well. Is there a easy way to do this? I'm not able to find any reference to the current socket from that scope.

**Comment by icgood** [comment]
I probably won't end up exposing the socket here in SmtpSession because things like close require some extra logic with SSL and also it's usually best to flush output buffers and return a status reply saying what's going on.

But, I do understand the need. The SMTP RFCs reserve the response codes `221` and `421` for the server to tell the client that it is closing the socket. My initial thought is slimta should check for those statuses on return from the SmtpSession handlers, and initiate connection closing if it sees either code. The other option is to add an exception that a handler can raise, with optional `Reply` object, that signals the connection to close. The former idea is more RFC-compliant but the latter is more flexible. I'll have to think about it a bit, but I think it's a good 3.0.0 addition.

**Comment by thestick613** [comment]
Theoretically, i could connect to a SmtpEdge and keep on RSET-ing for hours. There's no way to close the socket for an offending client. Thanks!

**Comment by icgood** [comment]
So I don't forget, it might be worth adding a `self.session.started` [datetime object](https://docs.python.org/2/library/datetime.html#datetime-objects) that handles can leverage.

**Comment by thestick613** [comment]
Isn't 521 the same?

**Comment by icgood** [comment]
521 is not included in any of the regular SMTP RFCs (821, 2821, 5321). It appears to be the subject of an experimental RFC 1846, which does not require closing the connection immediately (and appears to suggest not to).
