### ISSUE TITLE
No way to do the following scenario in 3.0.0 easier than in 2.0.0

### ISSUE THREAD

**Issue by thestick613** [slimta/python-slimta#67]
Acquire an Envelope
- inspect the recipient and the sender
- External logic decides an ip and an ehlo
- Attempt the envelope thru a MxSmtpRelay which is constructed with a socket_creator which uses the said ip and using the decided ehlo.

There are benefits in using the MxSmtpRelay class, because it can re-use a non-closed socket, via the `idle_timeout` parameter. The new `3.0.0` capability of providing the `echlo_as` as a function isn't very usefull, as you may want to use a different ehlo on the same MxSmtpRelay class. I just can't imagine using it, because i create an object which holds multiple MxSmtpRelay instances, each with it's own source_ip.

I've worked around this in 2.0.0 and 3.0.0 looks as difficult.

**Comment by icgood** [comment]
Interesting. So you're saying you'd like to re-EHLO on a connection that has already EHLO'ed, using logic that is based on the sender or recipient of the Envelope? Typically the EHLO is done once per-connection--although it is allowed many times--because it typically describes the connected client.

To understand your scenario better, I will probably need to know all the "variables" that go in to your choice of EHLO strings. For example:

* Bind host/port?
* Peer host/port?
* Envelope sender/rcpt information?
* TLS status?

**Comment by thestick613** [comment]
I just realized that i can keep an 2d array of MxSmtpRelays, each one with it's own (ehlo) X (bind_ip). I'm not really sure every email server implementation understands re-EHLO-ing after a succesful message, so maybe just one ehlo per smtp transaction, at the beginning, is the safest way. This way, i can have my cake, and eat it too. I'm still not sure what i can do now with the `ehlo_as` function, though, but it doesn't matter anymore. I forgot that i'm only ehloing once per connection.

To answer your question, just inspecting the sender and the recipient in an Envelope is usually enough to determine what ip and ehlo to use, for me. Different services might have bigger requirements.

**Comment by thestick613** [comment]
More being said, i'm not sure how i would change the delivery mechanism in the future, so i'm overplanning and thinking of any possible logic i might want later on. I'd like to make it as flexible as possible, so i don't have to change it anywhere else, except in a configuration.
